foo: foo goods ccc
feign:
  hystrix:
    enabled: true
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    durid:
      initialsize: 2

#mybatis
mybatis:
  type-aliases-package: com.lanou.model
  mapper-locations: classpath:mappers/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.lanou.util.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql